### ISSUE TITLE
where is d vendor folder ? its not in git

### ISSUE THREAD

**Issue by shashikant3** [technodweep/gst-invoice#1]
require(D:\xampp6\htdocs\basic\web/../vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp6\htdocs\basic\web\index.php on line 7

**Comment by sandeepkurien** [comment]
In the basic directory run the command 
`composer install`

**Comment by sandeepkurien** [comment]
Also run the following in the project directory
`composer update`
