### ISSUE TITLE
Unable to open pages other pages

### ISSUE THREAD

**Issue by kunalnaiya112** [technodweep/gst-invoice#2]
hi,
   Only home page is opening other pages like Home
Orders
Products
Customer
Settings
Tax Settings
Login are not opening....getting error.
![error](https://user-images.githubusercontent.com/31254906/29581173-2658253c-8796-11e7-8e5e-140f5ab4fc79.jpg)

**Comment by sandeepkurien** [comment]
I have updated the readme file.
You need to create a virtualhost as mentioned in readme
